### ISSUE TITLE
TODO for v1.0 

### ISSUE THREAD

**Issue by robbietuk** [UCL/STIR-GATE-Connection#37]
- [ ] mCT #26 (optional?)

- [x] README 
  - Project software Requirements (STIR and GATE, root?)
  - Better discription outlining the usage of the project (feedback and help is needed)
 

- [x] Scanner view offset #19 checked (optional: test scripts)

- [x] Fix file structure
  - [x] `Output/` directory should not have any scripts or templates in it. The templates need to be moved.
  - [ ] The directory name `VoxelisedSimulation/` is possibly not suitable anymore.
  - [x] There are old scripts in `'images/` for some reason... (have been moved)

- [ ] PATHS... and setting enviromental variables. The idea here is to define things like `$SGC_HOME` as the STIR-GATE-Connection project directory and then set all paths from there. In some places paths are defined relatively e.g.`../PATH/TO/FILE` 

- [ ] AttenuationConv.dat #44

**Comment by robbietuk** [comment]
Replaced by #56
