### ISSUE TITLE
v1.1 TODO

### ISSUE THREAD

**Issue by robbietuk** [UCL/STIR-GATE-Connection#56]
Since v1.0 has been created, preparing for the next (sub-)release. Some of these issues/PRs are leftover from the previous #37 

- [ ] mCT #26 
- [x] Scatter Estimation #50 
- [x] PATHS... and setting enviromental variables. The idea here is to define things like `$SGC_HOME` as the STIR-GATE-Connection project directory and then set all paths from there. In some places paths are defined relatively e.g.`../PATH/TO/FILE` #74 

- [ ] AttenuationConv.dat #44

- [x] Energy information should not be hardcoded #54 
- [x] General corrections computation script #70 
- [x] Move corrections computation scripts out of VoxelisedSimulation #75  
- [x] Reconstruction (OSEM) example #76

**Comment by robbietuk** [comment]
Closing because the milestone tracker is more useful than an issue
